import React from 'react';

export interface Tool {
  name: string;
  logo: string;
  url: string;
  article: string;
}

const placeholderArticle = `
  <p>Discover how this tool can revolutionize your workflow. With its advanced AI capabilities, it's designed to streamline processes, enhance creativity, and boost productivity.</p>
  <h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">Key Features</h3>
  <ul class="list-disc list-inside space-y-2">
    <li><strong>Intuitive Interface:</strong> Get started in minutes with a user-friendly design that requires no technical expertise.</li>
    <li><strong>Powerful AI Engine:</strong> Leverage state-of-the-art algorithms to achieve high-quality results quickly and efficiently.</li>
    <li><strong>Seamless Integration:</strong> Connect with your favorite apps and platforms to create a unified and automated workflow.</li>
    <li><strong>Scalable Solutions:</strong> Whether you're a solo creator or a large enterprise, this tool scales to meet your needs.</li>
  </ul>
  <h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">Who is it for?</h3>
  <p>This tool is perfect for content creators, marketers, designers, developers, and anyone looking to harness the power of AI. It helps professionals save time on repetitive tasks and focus on what truly matters: creating impactful work.</p>
`;

const soraLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="2" width="96" height="96" rx="10" stroke="currentColor" strokeWidth="4"/><path d="M30 70 C 40 50, 60 50, 70 70" stroke="currentColor" strokeWidth="4"/><path d="M30 30 C 40 50, 60 50, 70 30" stroke="currentColor" strokeWidth="4"/></svg>`;
const runwayLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 L 50 20 L 80 80 Z" stroke="currentColor" strokeWidth="4"/></svg>`;
const pikaLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 20 H 80 V 80 H 20 Z" fill="currentColor"/><circle cx="50" cy="50" r="20" fill="black"/></svg>`;
const kaiberLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M50 20 L 80 50 L 50 80 L 20 50 Z" stroke="currentColor" strokeWidth="4"/></svg>`;
const gen2Logo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="60" height="60" rx="10" stroke="currentColor" strokeWidth="4"/><text x="50" y="60" textAnchor="middle" fill="currentColor" fontSize="30" fontWeight="bold">G2</text></svg>`;
const veedLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M25 25 L 50 75 L 75 25" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/></svg>`;
const synthesiaLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M70 25 C 40 25, 40 75, 70 75" stroke="currentColor" strokeWidth="4"/><path d="M30 75 C 60 75, 60 25, 30 25" stroke="currentColor" strokeWidth="4"/></svg>`;
const invideoLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="25" y="25" width="10" height="50" fill="currentColor"/><path d="M55 25 L 75 50 L 55 75" stroke="currentColor" strokeWidth="4"/></svg>`;
const heygenLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 25 H 80 M 20 50 H 80 M 20 75 H 50" stroke="currentColor" strokeWidth="4" /><rect x="60" y="65" width="20" height="20" fill="currentColor"/></svg>`;
const lumaAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M50 10 C 80 10, 90 40, 90 50 S 80 90, 50 90 S 10 60, 10 50 S 20 10, 50 10" stroke="currentColor" strokeWidth="4"/></svg>`;
const captionsAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="30" width="60" height="40" rx="5" stroke="currentColor" strokeWidth="4"/><path d="M30 50 H 70" stroke="currentColor" strokeWidth="3"/><path d="M30 60 H 50" stroke="currentColor" strokeWidth="3"/></svg>`;


const pictoryLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 20 V 80 H 80" stroke="currentColor" strokeWidth="4"/><path d="M40 40 L 60 60 M 60 40 L 40 60" stroke="currentColor" strokeWidth="4"/></svg>`;
const flikiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 L 70 50 L 30 80 Z" stroke="currentColor" strokeWidth="4"/><path d="M70 20 V 80" stroke="currentColor" strokeWidth="4"/></svg>`;
const descriptLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="60" height="60" rx="10" stroke="currentColor" strokeWidth="4"/><path d="M40 40 L 40 60 L 60 60" stroke="currentColor" strokeWidth="4"/></svg>`;
const opusClipLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 C 80 20, 80 80, 30 80" stroke="currentColor" strokeWidth="4"/><rect x="25" y="45" width="10" height="10" fill="currentColor"/></svg>`;

// New Video Tool Logos
const flexClipLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 30 L 50 30 L 80 70 L 50 70 Z" stroke="currentColor" strokeWidth="4"/></svg>`;
const vislaLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 50 L 50 20 L 80 50 L 50 80 Z" stroke="currentColor" strokeWidth="4"/><path d="M50 20 V 80" stroke="currentColor" strokeWidth="2" stroke-dasharray="4 4"/></svg>`;
const elaiIoLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 L 70 20 L 70 80 L 30 80" stroke="currentColor" strokeWidth="4"/><path d="M30 50 H 70" stroke="currentColor" strokeWidth="4"/></svg>`;
const colossyanLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="60" height="60" rx="10" stroke="currentColor" strokeWidth="4"/><rect x="35" y="35" width="30" height="30" rx="5" stroke="currentColor" strokeWidth="4"/></svg>`;
const dIdLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 25 H 50 C 70 25, 70 75, 50 75 H 30" stroke="currentColor" strokeWidth="4"/></svg>`;
const hourOneLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="15" y="15" width="70" height="70" rx="10" stroke="currentColor" strokeWidth="4"/><path d="M50 25 V 50 H 75" stroke="currentColor" strokeWidth="4"/></svg>`;
const synthesysLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 C 40 40, 60 40, 80 80 M 20 20 C 40 60, 60 60, 80 20" stroke="currentColor" strokeWidth="4"/></svg>`;
const genmoLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M50 10 C 20 40, 20 60, 50 90 C 80 60, 80 40, 50 10" stroke="currentColor" strokeWidth="4"/></svg>`;
const moonvalleyLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M70 20 A 30 30 0 1 0 70 80" stroke="currentColor" strokeWidth="4"/><path d="M65 25 A 25 25 0 1 0 65 75" fill="currentColor"/></svg>`;
const domoAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="60" height="60" rx="10" stroke="currentColor" strokeWidth="4"/><path d="M40 40 H 60 L 60 60" stroke="currentColor" strokeWidth="4"/></svg>`;
const viggleAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 Q 50 20 80 80" stroke="currentColor" strokeWidth="4"/><path d="M35 80 Q 50 50 65 80" stroke="currentColor" strokeWidth="4"/></svg>`;
const haiperAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 50 H 80 M 50 20 V 80" stroke="currentColor" strokeWidth="4"/><rect x="35" y="35" width="30" height="30" rx="5" stroke="currentColor" strokeWidth="4"/></svg>`;

// New Long Video Tool Logos
const lumen5Logo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 20 L 20 80 L 80 80" stroke="currentColor" strokeWidth="4"/><path d="M50 50 H 80 V 20 H 50 Z" fill="currentColor"/></svg>`;
const rawShortsLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 L 70 20 L 70 60 L 50 80 L 30 60 Z" stroke="currentColor" strokeWidth="4"/></svg>`;
const waveVideoLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10 50 C 30 30, 50 70, 70 50 S 90 30, 90 30" stroke="currentColor" strokeWidth="4"/></svg>`;
const wisecutLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 50 L 80 50 M 50 20 L 40 50 L 50 80" stroke="currentColor" strokeWidth="4"/><path d="M70 35 L 70 65" stroke="currentColor" strokeWidth="4"/></svg>`;
const munchLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 C 50 20, 50 20, 80 80 Z" stroke="currentColor" strokeWidth="4"/><path d="M35 80 C 50 50, 50 50, 65 80" stroke="currentColor" strokeWidth="4"/></svg>`;
const vidyoAiLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 30 L 50 70 L 80 30" stroke="currentColor" strokeWidth="4"/><rect x="45" y="65" width="10" height="10" fill="currentColor"/></svg>`;
const quickvidLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 20 L 80 50 L 20 80 Z" stroke="currentColor" strokeWidth="4"/><path d="M50 35 L 80 50 L 50 65" stroke="currentColor" strokeWidth="2"/></svg>`;
const clipchampLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 30 H 80 M 20 70 H 80 M 50 30 V 70" stroke="currentColor" strokeWidth="4"/><rect x="40" y="40" width="20" height="20" fill="currentColor"/></svg>`;
const typeStudioLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 V 80 M 20 20 H 40" stroke="currentColor" strokeWidth="4"/><path d="M60 20 L 60 80 L 80 80 L 80 50 L 60 50" stroke="currentColor" strokeWidth="4"/></svg>`;
const kamuaLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 V 20 L 50 50 L 80 20 V 80" stroke="currentColor" strokeWidth="4"/></svg>`;

// Placeholder logos for new categories
const genericWritingLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 L30 40 L50 60 L70 40 L80 80 M35 70 H 65" stroke="currentColor" strokeWidth="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const genericAudioLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 40 V 60 M 40 30 V 70 M 50 20 V 80 M 60 30 V 70 M 70 40 V 60" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/></svg>`;
const genericChatbotLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 20 H 80 V 70 H 40 L 20 90 V 70 H 20 Z" stroke="currentColor" strokeWidth="4" stroke-linejoin="round"/></svg>`;
const genericCodeLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 40 L 20 50 L 30 60 M 70 40 L 80 50 L 70 60 M 45 30 L 55 70" stroke="currentColor" strokeWidth="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const genericResearchLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="20" y="20" width="50" height="50" rx="5" stroke="currentColor" strokeWidth="4"/><path d="M65 65 L 80 80" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/></svg>`;
const genericBusinessLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 V 30 H 80 V 80 M 20 80 H 80 M 40 80 V 60 H 60 V 80 M 40 50 H 60" stroke="currentColor" strokeWidth="4" stroke-linejoin="round" stroke-linecap="round"/></svg>`;
const genericProductivityLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 30 L 40 50 L 80 20 M 20 70 L 40 90 L 80 60" stroke="currentColor" strokeWidth="4" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const genericDataLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 80 V 60 M 40 80 V 40 M 60 80 V 20 M 80 80 V 50" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/></svg>`;
const genericEducationLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 40 L 50 20 L 80 40 L 50 60 Z" stroke="currentColor" strokeWidth="4" stroke-linejoin="round" stroke-linecap="round"/><path d="M30 50 V 70 C 30 80, 50 90, 50 90 C 50 90, 70 80, 70 70 V 50" stroke="currentColor" strokeWidth="4" stroke-linejoin="round" stroke-linecap="round"/></svg>`;
const genericHealthcareLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M50 20 V 80 M 20 50 H 80" stroke="currentColor" strokeWidth="6" stroke-linecap="round"/><path d="M30 80 Q 50 60 70 80" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/></svg>`;
const genericLegalFinanceLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 80 H 70 M 50 80 V 30 M 20 30 H 80" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/><path d="M40 50 C 40 40, 60 40, 60 50 S 40 60, 60 60" stroke="currentColor" strokeWidth="4"/></svg>`;
const genericEcommerceLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 30 H 80 L 70 60 H 30 Z" stroke="currentColor" strokeWidth="4"/><rect x="30" y="70" width="10" height="10" rx="2" stroke="currentColor" strokeWidth="4"/><rect x="60" y="70" width="10" height="10" rx="2" stroke="currentColor" strokeWidth="4"/></svg>`;
const genericHrLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="35" y="25" width="30" height="30" rx="5" stroke="currentColor" strokeWidth="4"/><path d="M30 80 C 40 60, 60 60, 70 80" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/></svg>`;
const genericGamingLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 50 H 40 M 60 50 H 80 M 30 40 V 60 M 70 40 V 60" stroke="currentColor" strokeWidth="4" stroke-linecap="round"/><rect x="10" y="30" width="80" height="40" rx="10" stroke="currentColor" strokeWidth="4"/></svg>`;
const genericStorytellingLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M30 20 H 70 V 80 H 30 Z" stroke="currentColor" strokeWidth="4"/><path d="M30 80 L 50 70 L 70 80" stroke="currentColor" strokeWidth="4"/><path d="M40 35 H 60 M 40 50 H 60 M 40 65 H 50" stroke="currentColor" strokeWidth="3"/></svg>`;
const genericAutomationLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="25" y="25" width="20" height="20" rx="4" stroke="currentColor" strokeWidth="4"/><rect x="55" y="55" width="20" height="20" rx="4" stroke="currentColor" strokeWidth="4"/><path d="M35 45 V 65 H 55" stroke="currentColor" strokeWidth="4"/><path d="M45 35 H 65 V 55" stroke="currentColor" strokeWidth="4" stroke-dasharray="4 4"/></svg>`;
const genericSecurityLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M50 10 L 90 30 V 60 C 90 80, 50 90, 50 90 C 50 90, 10 80, 10 60 V 30 Z" stroke="currentColor" strokeWidth="4" stroke-linejoin="round"/><rect x="40" y="45" width="20" height="20" rx="4" stroke="currentColor" strokeWidth="4"/><path d="M50 65 V 75" stroke="currentColor" strokeWidth="4"/></svg>`;
const genericSandboxLogo = `<svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20 70 L 30 30 H 70 L 80 70 H 20 Z" stroke="currentColor" strokeWidth="4"/><path d="M20 70 C 40 80, 60 80, 80 70" stroke="currentColor" strokeWidth="4"/></svg>`;

export const INITIAL_VIDEO_TOOLS: Tool[] = [
  { name: 'Imagine art', logo: '<img src="https://ik.imagekit.io/bensusx9i/jjjjknbkm(1)(1)_5_11zon.webp" alt="Imagine art Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.imagine.art/', article: `<p>Unleash your inner artist with Imagine Art, a powerful AI image generator that transforms your text prompts into breathtaking visuals. Describe any scene, character, or concept, and watch as the AI brings your imagination to life in stunning detail.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Text-to-Image Generation:</strong> Create high-resolution images and artwork from simple text descriptions.</li><li><strong>Multiple Art Styles:</strong> Explore a vast range of artistic styles, from photorealistic to anime, oil painting, and more.</li><li><strong>Image Remixing:</strong> Upload an existing image and use AI to reinterpret or add new elements based on your prompts.</li></ul><p class="mt-4">Perfect for artists, designers, and hobbyists, Imagine Art is your gateway to limitless creative expression without needing complex software.</p>` },
  { name: 'Pollo Ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/ljkhhkhkk(1)(1)_7_11zon.webp" alt="Pollo Ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.pollo.ai/', article: `<p>Pollo AI is an intuitive and versatile AI creation suite that excels at generating unique images and videos from text. Its user-friendly interface makes it easy for anyone to produce high-quality, engaging visual content for social media, marketing, or personal projects.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Consistent Character Generation:</strong> Create consistent characters across multiple images for storytelling and branding.</li><li><strong>AI Video from Text:</strong> Animate your ideas by turning text prompts into short, dynamic video clips.</li><li><strong>Style Adaptation:</strong> The AI learns from your inputs to generate visuals that match your unique aesthetic.</li></ul><p class="mt-4">Pollo AI is ideal for content creators and marketers looking for a fast and simple way to generate custom visuals that stand out.</p>` },
  { name: 'Higgsfield', logo: '<img src="https://ik.imagekit.io/bensusx9i/higgsfield_logo(1)(1)_9_11zon.webp" alt="Higgsfield Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://higgsfield.ai/', article: `<p>Higgsfield allows you to create your very own personal AI video actor. By training the AI with a short video of a person, you can generate a digital character that can be directed to speak, act, and express emotions in any video you create. It's like having a virtual actor on call 24/7.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Personal AI Actor Creation:</strong> Train a unique AI character from a short video of anyone—yourself, a friend, or a fictional character.</li><li><strong>Text-to-Video with Your Actor:</strong> Simply type a script, and your AI actor will perform it, generating a complete video.</li><li><strong>Consistent Character Performance:</strong> Use your trained AI actor across multiple videos for consistent branding and storytelling.</li></ul><p class="mt-4">Higgsfield is a groundbreaking tool for creators who want to produce highly personalized and character-driven video content without cameras or complex animation software.</p>` },
  { name: 'iMyFone', logo: '<img src="https://ik.imagekit.io/bensusx9i/unnamed-1_4_11zon.webp" alt="iMyFone Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.imyfone.com/', article: `<p>iMyFone offers a suite of powerful multimedia tools enhanced with AI to solve common creative challenges. From video editing to photo enhancement, its AI features are designed to repair, improve, and transform your media with just a few clicks.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Video & Photo Enhancement:</strong> Automatically upscale resolution, reduce noise, and improve the clarity of your media files.</li><li><strong>AI Object Removal:</strong> Effortlessly erase unwanted people or objects from your photos and videos.</li><li><strong>AI Voice Changer:</strong> Modify your voice in real-time with a wide range of effects for gaming, streaming, or content creation.</li></ul><p class="mt-4">iMyFone is the perfect toolkit for anyone looking to quickly fix and elevate the quality of their photos and videos using smart, automated AI.</p>` },
  { name: 'Artlist', logo: '<img src="https://ik.imagekit.io/bensusx9i/Copilot_20251019_125715(1)_11zon.png" alt="Artlist Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://artlist.io/', article: `<p>Artlist is the ultimate creative ecosystem for video creators, offering a vast library of high-quality, royalty-free assets. It's the go-to platform for filmmakers, YouTubers, and marketers who need premium music, sound effects, stock footage, and video templates to elevate their projects.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI-Powered Search:</strong> Quickly find the perfect song or video clip with an intelligent search engine that understands creative intent.</li><li><strong>Extensive Asset Library:</strong> Gain unlimited access to a constantly growing catalog of assets from top-tier artists and filmmakers.</li><li><strong>Simple, Universal Licensing:</strong> A straightforward subscription covers all your projects, from social media to commercial ads, worry-free.</li></ul><p class="mt-4">Artlist streamlines the creative workflow by providing all the necessary assets under one simple license, empowering creators to produce stunning content without limits.</p>` },
  { name: 'Vidnoz', logo: '<img src="https://ik.imagekit.io/bensusx9i/4KWfOYnR_400x400(1)(1)_11zon(1).jpg" alt="Vidnoz Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.vidnoz.com/', article: `<p>Vidnoz is a comprehensive AI video platform that makes professional video creation accessible to everyone. Generate engaging videos complete with realistic AI avatars, voiceovers, and dynamic templates without needing any cameras or microphones.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Realistic AI Avatars:</strong> Choose from a diverse library of over 300 AI avatars to narrate your scripts.</li><li><strong>AI Voice Cloning:</strong> Create a digital clone of your own voice for personalized voiceovers in multiple languages.</li><li><strong>Automated Text-to-Video:</strong> Instantly convert your scripts, articles, or prompts into fully-edited videos with visuals and audio.</li></ul><p class="mt-4">Vidnoz is perfect for businesses and educators who want to produce high-quality training, marketing, and communication videos efficiently.</p>` },
  { name: 'VidFly', logo: '<img src="https://ik.imagekit.io/bensusx9i/vidfly-icon-filled-256(1)(1)(1)_15_11zon.webp" alt="VidFly Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://vidfly.ai/', article: `<p>VidFly leverages AI to help you create captivating videos with incredible speed. Its smart engine analyzes your content to suggest edits, add effects, and generate visuals, turning the complex task of video production into a simple, automated process.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Content Repurposing:</strong> Transform blog posts, podcasts, or webinars into engaging social media videos automatically.</li><li><strong>Smart Video Editor:</strong> The AI identifies key moments, removes awkward silences, and suggests compelling cuts.</li><li><strong>Automated Subtitle Generation:</strong> Instantly generate and animate accurate subtitles to make your videos more accessible and engaging.</li></ul><p class="mt-4">Ideal for social media managers and content creators, VidFly is the fastest way to produce a steady stream of high-quality video content.</p>` },
  { name: 'Leonardo', logo: '<img src="https://ik.imagekit.io/bensusx9i/leonardo-logo_1_-removebg-preview(1)_11_11zon.webp" alt="Leonardo Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://leonardo.ai/', article: `<p>Leonardo.Ai is a complete creative suite for generating exceptional visual assets using AI. Renowned for its high-quality, fine-tuned models, it empowers artists, game developers, and designers to create stunning characters, environments, and concept art with unparalleled control.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Fined-Tuned AI Models:</strong> Access a library of specialized models trained for specific styles like photorealism, fantasy, and pixel art.</li><li><strong>AI Canvas:</strong> An infinite canvas where you can edit, expand, and refine your AI generations with surgical precision.</li><li><strong>3D Texture Generation:</strong> Create seamless, tileable textures for 3D models from simple text prompts.</li></ul><p class="mt-4">Leonardo is the ultimate tool for creative professionals who demand high-fidelity results and deep control over the AI generation process.</p>` },
  { name: 'DeeVid AI', logo: '<img src="https://ik.imagekit.io/bensusx9i/22247730-deevid-logo-422x422-removebg-preview(1)_14_11zon.webp" alt="DeeVid AI Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://deevid.ai/', article: `<p>DeeVid AI specializes in creating deep, emotionally resonant video content through the power of artificial intelligence. Its platform focuses on generating realistic human presenters and crafting compelling narratives that connect with your audience on a personal level.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Emotionally-Aware AI Avatars:</strong> Generate videos with AI presenters that display nuanced emotions and natural gestures.</li><li><strong>AI Storytelling Assistant:</strong> Get help structuring your script and narrative to maximize viewer engagement and impact.</li><li><strong>Personalized Video Campaigns:</strong> Automatically generate thousands of unique video variations with personalized details for each viewer.</li></ul><p class="mt-4">This tool is perfect for marketing and sales teams aiming to build deeper customer relationships through scalable, personalized video outreach.</p>` },
  { name: 'PIXLR', logo: '<img src="https://ik.imagekit.io/bensusx9i/X4uS5WUa_400x400(1)(1)_13_11zon.webp" alt="PIXLR Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://pixlr.com/', article: `<p>PIXLR is a household name in online photo editing, now supercharged with a suite of powerful AI tools. It combines a user-friendly interface with advanced AI capabilities, making professional-level photo editing and design accessible to everyone, right in the browser.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>One-Click AI Background Removal:</strong> Instantly and precisely remove the background from any image.</li><li><strong>Generative Fill & Expand:</strong> Seamlessly remove unwanted objects or expand your image canvas with AI-generated content.</li><li><strong>AI Photo Enhancement:</strong> Automatically adjust colors, lighting, and sharpness to make your photos look their best in a single click.</li></ul><p class="mt-4">PIXLR is the go-to tool for anyone needing fast, powerful, and intuitive photo editing, from social media enthusiasts to professional photographers.</p>` },
  { name: 'Zebracat', logo: '<img src="https://ik.imagekit.io/bensusx9i/zebracat-icon-filled-256(1)(1)_6_11zon.webp" alt="Zebracat Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.zebracat.ai/', article: `<p>Zebracat is an AI-powered creative platform that automates the production of branded video and image content. Simply input your brand guidelines and a text prompt, and Zebracat's AI will generate a variety of on-brand marketing assets, from social media videos to product banners.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Brand Analysis:</strong> The AI learns your brand's visual identity from your website to ensure all content is consistent.</li><li><strong>Multi-Format Content Generation:</strong> Create videos, images, and GIFs for different platforms from a single prompt.</li><li><strong>AI-Powered Media Library:</strong> Get access to a curated library of stock footage and music, with AI recommendations to fit your content.</li></ul><p class="mt-4">Zebracat is a massive time-saver for marketing teams and agencies needing to produce high-quality, branded content at scale.</p>` },
  { name: 'Fliki Ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/fliki-icon-filled-256-1(1)_10_11zon.webp" alt="Fliki Ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://fliki.ai/', article: `<p>Fliki is a revolutionary AI tool that transforms your text into engaging videos with realistic voiceovers. Turn blog posts, articles, or scripts into captivating video content in minutes, complete with stock footage, background music, and a wide selection of AI-generated voices.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Text-to-Video Creation:</strong> The AI analyzes your text and automatically finds relevant video clips and images to build your scenes.</li><li><strong>Ultra-Realistic AI Voices:</strong> Choose from over 1900 voices in 75+ languages to narrate your content with natural-sounding speech.</li><li><strong>Blog-to-Video Automation:</strong> Simply paste a URL, and Fliki's AI will summarize the content, create scenes, and generate a full video.</li></ul><p class="mt-4">Fliki is perfect for content creators, marketers, and educators who want to repurpose written content into dynamic videos with minimal effort.</p>` },
];

export const INITIAL_IMAGE_TOOLS: Tool[] = [
  { name: 'Leonardo', logo: '<img src="https://ik.imagekit.io/bensusx9i/leonardo-logo_1_-removebg-preview(1)_11_11zon.webp" alt="Leonardo Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://leonardo.ai/', article: `<p>Leonardo.Ai is a complete creative suite for generating exceptional visual assets using AI. Renowned for its high-quality, fine-tuned models, it empowers artists, game developers, and designers to create stunning characters, environments, and concept art with unparalleled control.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Fined-Tuned AI Models:</strong> Access a library of specialized models trained for specific styles like photorealism, fantasy, and pixel art.</li><li><strong>AI Canvas:</strong> An infinite canvas where you can edit, expand, and refine your AI generations with surgical precision.</li><li><strong>3D Texture Generation:</strong> Create seamless, tileable textures for 3D models from simple text prompts.</li></ul><p class="mt-4">Leonardo is the ultimate tool for creative professionals who demand high-fidelity results and deep control over the AI generation process.</p>` },
];

export const LONG_VIDEO_TOOLS: Tool[] = [
  { name: 'Zebracat', logo: '<img src="https://ik.imagekit.io/bensusx9i/zebracat-icon-filled-256(1)(1)_6_11zon.webp" alt="Zebracat Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.zebracat.ai/', article: `<p>Zebracat is an AI-powered creative platform that automates the production of branded video and image content. Simply input your brand guidelines and a text prompt, and Zebracat's AI will generate a variety of on-brand marketing assets, from social media videos to product banners.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Brand Analysis:</strong> The AI learns your brand's visual identity from your website to ensure all content is consistent.</li><li><strong>Multi-Format Content Generation:</strong> Create videos, images, and GIFs for different platforms from a single prompt.</li><li><strong>AI-Powered Media Library:</strong> Get access to a curated library of stock footage and music, with AI recommendations to fit your content.</li></ul><p class="mt-4">Zebracat is a massive time-saver for marketing teams and agencies needing to produce high-quality, branded content at scale.</p>` },
  { name: 'Colossyan', logo: '<img src="https://ik.imagekit.io/bensusx9i/images(1)_8_11zon.webp" alt="Colossyan Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.colossyan.com/', article: `<p>Colossyan makes professional video production scalable and stress-free. Its AI video generator allows you to create high-quality training and marketing videos featuring AI avatars, translating your content into multiple languages with the click of a button.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Script Assistant:</strong> Leverage AI to help write and refine your video scripts for maximum clarity and impact.</li><li><strong>Auto-Translation:</strong> Instantly translate your video scripts and voiceovers into dozens of languages to reach a global audience.</li><li><strong>Diverse AI Avatars:</strong> Choose from a wide selection of commercially-usable AI presenters to be the face of your videos.</li></ul><p class="mt-4">Colossyan is the ideal solution for corporate learning, development, and marketing teams looking to produce professional video content efficiently.</p>` },
  { name: 'Fliki Ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/fliki-icon-filled-256-1(1)_10_11zon.webp" alt="Fliki Ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://fliki.ai/', article: `<p>Fliki is a revolutionary AI tool that transforms your text into engaging videos with realistic voiceovers. Turn blog posts, articles, or scripts into captivating video content in minutes, complete with stock footage, background music, and a wide selection of AI-generated voices.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Text-to-Video Creation:</strong> The AI analyzes your text and automatically finds relevant video clips and images to build your scenes.</li><li><strong>Ultra-Realistic AI Voices:</strong> Choose from over 1900 voices in 75+ languages to narrate your content with natural-sounding speech.</li><li><strong>Blog-to-Video Automation:</strong> Simply paste a URL, and Fliki's AI will summarize the content, create scenes, and generate a full video.</li></ul><p class="mt-4">Fliki is perfect for content creators, marketers, and educators who want to repurpose written content into dynamic videos with minimal effort.</p>` },
  { name: 'VEED', logo: '<img src="https://ik.imagekit.io/bensusx9i/idZ6QLGyv0-removebg-preview_16_11zon.webp" alt="VEED Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.veed.io/', article: `<p>VEED is a powerful online video editor packed with intelligent AI features to simplify your workflow. It's designed for creators and marketers who need to produce professional-looking videos quickly, without getting bogged down in complex editing software.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Automatic Subtitle Generation:</strong> Instantly add accurate subtitles to your videos to improve accessibility and engagement.</li><li><strong>AI Background Noise Removal:</strong> Clean up your audio with one click, removing wind, traffic, and other distracting sounds.</li><li><strong>Eye Contact Correction:</strong> The AI cleverly adjusts your gaze to make it look like you're always looking directly at the camera.</li></ul><p class="mt-4">VEED is the ultimate all-in-one editor for anyone who wants to edit videos faster and smarter using the power of AI.</p>` },
  { name: 'Pictory', logo: '<img src="https://ik.imagekit.io/bensusx9i/pictory_500-removebg-preview(1)_18_11zon.webp" alt="Pictory Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://pictory.ai/', article: `<p>Pictory uses the power of AI to transform your long-form content into short, highly-shareable videos in minutes. Whether you have a script, a blog post, or a webinar recording, Pictory's AI can automatically create a professional video complete with stock footage, music, and voiceover.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Script-to-Video:</strong> The AI analyzes your script and intelligently selects visuals from a massive library to match your message.</li><li><strong>Article-to-Video:</strong> Paste a blog post URL, and Pictory's AI will create a summary video with key highlights.</li><li><strong>AI Voiceover:</strong> Choose from a range of realistic AI voices to narrate your video, or automatically sync your own audio track.</li></ul><p class="mt-4">Pictory is a must-have tool for marketers and content creators looking to maximize their content's reach by effortlessly repurposing it for video.</p>` },
  { name: 'Synthesia', logo: '<img src="https://ik.imagekit.io/bensusx9i/imagesfhvn_19_11zon.webp" alt="Synthesia Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.synthesia.io/', article: `<p>Synthesia is a leading AI video generation platform that lets you create professional videos with photorealistic AI avatars. Eliminate the need for cameras, actors, and microphones by simply typing your script and letting the AI generate a high-quality video in over 120 languages.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Photorealistic AI Avatars:</strong> Select from a diverse library of over 150 stock avatars or create a custom digital twin of yourself.</li><li><strong>Natural Text-to-Speech:</strong> Generate professional voiceovers with consistent quality and a wide range of emotional tones.</li><li><strong>AI Script Assistant:</strong> Leverage AI to help you write, shorten, and optimize your video scripts for better engagement.</li></ul><p class="mt-4">Synthesia is trusted by thousands of companies for creating scalable training, marketing, and corporate communication videos with ease.</p>` },
  { name: 'HeyGen', logo: '<img src="https://ik.imagekit.io/bensusx9i/apps.10279.13b71432-e992-43be-af65-123449130199.19fc4577-aa0a-4a42-b54d-4d75859dc0c8_20_11zon.webp" alt="HeyGen Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.heygen.com/', article: `<p>HeyGen is a versatile AI video platform designed for creating engaging, studio-quality videos with generative AI. From personalized sales pitches to dynamic marketing content, HeyGen's powerful tools allow you to produce content at scale, featuring customizable avatars and realistic voices.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Video Translation:</strong> Upload a video and the AI will translate the audio, match the voice style, and sync your lip movements.</li><li><strong>Custom Avatars:</strong> Create your own high-fidelity AI avatar for a truly personalized and consistent brand presence.</li><li><strong>Streaming Avatar:</strong> Integrate a real-time AI avatar into your live streams for a unique and interactive experience.</li></ul><p class="mt-4">HeyGen is the perfect solution for sales, marketing, and L&D teams aiming to create impactful video content faster than ever before.</p>` },
  { name: 'AKOOL', logo: '<img src="https://ik.imagekit.io/bensusx9i/akool_21_11zon.webp" alt="AKOOL Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://akool.com/', article: `<p>AKOOL provides a suite of generative AI tools aimed at revolutionizing marketing and advertising content. Its platform enables the creation of hyper-realistic images, videos, and avatars, helping businesses produce high-impact, personalized campaigns that capture audience attention.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Face Swap:</strong> Realistically swap faces in images and videos for creative marketing and entertainment content.</li><li><strong>Talking Photos:</strong> Animate any portrait photo and make it speak your scripted words with natural lip-syncing.</li><li><strong>Personalized Video Generation:</strong> Create customized videos at scale, tailoring messages and visuals for individual customers.</li></ul><p class="mt-4">AKOOL is a powerful asset for advertising agencies and marketing teams looking to push creative boundaries with cutting-edge generative AI.</p>` },
  { name: 'Descript', logo: '<img src="https://ik.imagekit.io/bensusx9i/descript-icon-vrjwgsy86fm07riycz7zt63-removebg-preview(1)_22_11zon.webp" alt="Descript Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.descript.com/', article: `<p>Descript is an all-in-one audio and video editor that makes content creation as simple as editing a text document. Its powerful AI features transcribe your media, allowing you to edit your video or podcast by simply editing the text, saving countless hours of tedious work.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Edit by Transcript:</strong> Cut, copy, and paste your audio/video by editing the automatically generated text transcript.</li><li><strong>Overdub & Voice Cloning:</strong> Correct audio mistakes or add new words by simply typing them, using an ultra-realistic clone of your voice.</li><li><strong>Studio Sound:</strong> With one click, the AI removes background noise and enhances voice quality to sound like it was recorded in a studio.</li></ul><p class="mt-4">Descript is an indispensable tool for podcasters, YouTubers, and anyone who wants a faster, more intuitive way to edit spoken-word media.</p>` },
  { name: 'InVideo', logo: '<img src="https://ik.imagekit.io/bensusx9i/unnamedhfhb_24_11zon.webp" alt="InVideo Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://invideo.io/', article: `<p>InVideo's AI-powered online video editor empowers you to create stunning videos from your ideas in minutes. With a massive library of templates and an intelligent text-to-video generator, it's designed to make video creation fast, easy, and accessible for everyone, regardless of experience.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Text-to-Video:</strong> Input your script or text, and InVideo's AI will automatically create a video with matching scenes, music, and text overlays.</li><li><strong>Intelligent Scene Suggestions:</strong> The AI recommends relevant stock footage and images from its extensive library to fit your script.</li><li><strong>AI Voiceover Generation:</strong> Instantly convert your text to a natural-sounding voiceover to narrate your videos.</li></ul><p class="mt-4">InVideo is perfect for marketers, small businesses, and content creators who need to produce professional videos for any platform quickly.</p>` },
  { name: 'Ai Studios', logo: '<img src="https://ik.imagekit.io/bensusx9i/unnamedkhjknm_25_11zon.webp" alt="Ai Studios Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://aistudios.com/', article: `<p>AI Studios provides a comprehensive AI video solution for creating hyper-realistic virtual humans. Their platform is built for enterprises that need to produce high-quality, scalable video content for news, education, and corporate communications using state-of-the-art AI technology.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Real-Time AI Avatars:</strong> Generate broadcast-quality videos with virtual humans that feature lifelike movements and expressions.</li><li><strong>Text-to-Video Synthesis:</strong> Simply upload a script, and the platform produces a complete video with an AI anchor or presenter.</li><li><strong>Multi-Language Support:</strong> Create content with AI avatars that can speak multiple languages, enabling global communication effortlessly.</li></ul><p class="mt-4">AI Studios is tailored for media companies and large organizations requiring a robust, high-fidelity solution for AI-driven video production.</p>` },
  { name: 'Elai', logo: '<img src="https://ik.imagekit.io/bensusx9i/imagesjhgjkbn_30_11zon.webp" alt="Elai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://elai.io/', article: `<p>Elai.io is an AI video generation platform that lets you create customized video content with digital presenters from just text. It is designed to help businesses produce training videos, marketing materials, and narrated content at scale, without the costs associated with traditional video production.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Blog Post to Video:</strong> Convert any article or blog post URL into an engaging video with a presenter.</li><li><strong>Personalized AI Avatars:</strong> Create a digital version of yourself or choose from a library of diverse, realistic avatars.</li><li><strong>API for Scaled Production:</strong> Use the Elai API to automatically generate thousands of personalized videos for your customers or employees.</li></ul><p class="mt-4">Elai is an excellent choice for businesses looking to automate their video creation process for L&D, sales, and marketing purposes.</p>` },
  { name: 'Kapwing', logo: '<img src="https://ik.imagekit.io/bensusx9i/kapwing_23_11zon.webp" alt="Kapwing Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.kapwing.com/', article: `<p>Kapwing is a collaborative online video editor that integrates a suite of powerful AI tools to make content creation faster and easier. It's a browser-based platform perfect for teams and individual creators who want to edit, repurpose, and create stunning videos with smart, automated features.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Smart Cut:</strong> Automatically finds and removes silences in your video, saving you significant editing time.</li><li><strong>Auto-Subtitling:</strong> Generate subtitles for your video in seconds and customize them with various animations and styles.</li><li><strong>AI Video Generator:</strong> Create a video from scratch by providing a text prompt, and the AI will generate a sequence of clips.</li></ul><p class="mt-4">Kapwing is the ideal tool for social media managers, meme creators, and marketing teams who need a fast, collaborative, and AI-enhanced video editing solution.</p>` },
  { name: 'Renderforest', logo: '<img src="https://ik.imagekit.io/bensusx9i/RenderForest_2017-icon-removebg-preview_29_11zon.webp" alt="Renderforest Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.renderforest.com/', article: `<p>Renderforest is an all-in-one branding platform where you can create high-quality videos, logos, graphics, and websites with the help of AI. Its template-based approach simplifies the creative process, making professional design and video production accessible to everyone.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Logo Maker:</strong> Generate unique and professional logos for your brand based on your industry and style preferences.</li><li><strong>Intelligent Video Templates:</strong> The AI suggests video templates and scenes based on your script or description.</li><li><strong>AI Website Builder:</strong> Create a professional website in minutes with an AI that designs layouts and structures content for you.</li></ul><p class="mt-4">Renderforest is perfect for entrepreneurs and small businesses that need a comprehensive, easy-to-use solution for all their branding and marketing needs.</p>` },
];

export const VIRAL_SHORT_TOOLS: Tool[] = [
  { name: 'Short.ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/219620309-removebg-preview(1)_26_11zon.webp" alt="Short.ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.short.ai/', article: `<p>Short.ai is a powerful, text-based AI video editor designed to make video creation for businesses fast and effortless. It works like a document, allowing you to edit complex video projects by simply editing the text transcript. This intuitive approach dramatically speeds up the entire production workflow.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Text-Based Video Editing:</strong> Edit your video by cutting, pasting, and deleting words in the auto-generated transcript.</li><li><strong>AI Silence Removal:</strong> Instantly remove awkward pauses and filler words ("ums," "ahs") with a single click to create a polished final cut.</li><li><strong>Collaborative Cloud Platform:</strong> Work with your team in real-time, leaving comments and edits directly on the project.</li></ul><p class="mt-4">Short.ai is the perfect solution for marketing teams, corporate trainers, and businesses that need to produce professional videos for communication, training, and social media without the steep learning curve of traditional software.</p>` },
  { name: 'Klap', logo: '<img src="https://ik.imagekit.io/bensusx9i/7XMz-YQq_400x400-removebg-preview_27_11zon.webp" alt="Klap Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://klap.app/', article: `<p>Klap uses AI to turn your YouTube videos into a goldmine of viral short clips. Simply paste a YouTube link, and Klap's AI gets to work, identifying the best topics, cutting them into clips, reframing the video, and adding beautiful captions to make them ready for social media.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Topic Recognition:</strong> The AI understands the context of your video to extract clips based on the most engaging topics.</li><li><strong>Face Detection & Reframing:</strong> Automatically ensures the speaker is always in the center of the vertical frame.</li><li><strong>Virality Scoring:</strong> Each generated clip is given a score to help you identify the ones with the most viral potential.</li></ul><p class="mt-4">Klap is the perfect tool for YouTubers and thought leaders who want to effortlessly expand their presence on TikTok, Reels, and Shorts.</p>` },
  { name: 'Quso Ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/quso_ai_logo_28_11zon.webp" alt="Quso Ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://quso.ai/', article: `<p>Quso AI is a smart tool that helps you discover and create engaging short-form video content from podcasts and webinars. Its AI listens to your audio, identifies impactful questions and key moments, and turns them into shareable video clips perfect for social media.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Question Detection:</strong> The AI intelligently identifies questions asked in your content, a proven format for high engagement.</li><li><strong>Magic Clipping:</strong> Automatically extracts the most interesting and concise segments from long conversations.</li><li><strong>Dynamic Captions & Branding:</strong> Add your brand's colors and logo, and choose from various caption styles to match your identity.</li></ul><p class="mt-4">Quso AI is ideal for podcasters, coaches, and educators who want to leverage the power of their existing audio content to grow their social media following.</p>` },
];

export const WRITING_TOOLS: Tool[] = [
    { name: 'Rytr', logo: '<img src="https://ik.imagekit.io/bensusx9i/jgjgjkkj_38_11zon.webp" alt="Rytr Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://rytr.me/', article: `<p>Rytr is a powerful and affordable AI writing assistant that helps you create high-quality content in just a few seconds. From blog posts and emails to ad copy and social media updates, Rytr's AI can generate compelling text for virtually any use case across 30+ languages.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Multiple Use Cases:</strong> Choose from over 40 use cases, including blog outlines, product descriptions, and video ideas.</li><li><strong>Tone Adjustment:</strong> Select from more than 20 tones of voice to ensure your content matches your brand's personality.</li><li><strong>Built-in Plagiarism Checker:</strong> Ensure your generated content is original and unique before publishing.</li></ul><p class="mt-4">Rytr is perfect for copywriters, marketers, and entrepreneurs who need to produce great content faster and overcome writer's block.</p>` },
    { name: 'Frase', logo: '<img src="https://ik.imagekit.io/bensusx9i/hkdffkhvb_37_11zon.webp" alt="Frase Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.frase.io/', article: `<p>Frase is an all-in-one AI content workflow solution that helps you research, write, and optimize content that ranks on Google. It streamlines the entire SEO content creation process, from identifying topics to generating a fully optimized article, all within one platform.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Content Briefs:</strong> Automatically generates comprehensive SEO content briefs based on the top-ranking search results.</li><li><strong>AI Content Writer:</strong> Writes high-quality, SEO-focused drafts based on your briefs and target keywords.</li><li><strong>Content Optimization:</strong> Scores your content against competitors and provides specific recommendations for improvement.</li></ul><p class="mt-4">Frase is an essential tool for SEO specialists, content marketers, and agencies focused on creating content that drives organic traffic.</p>` },
    { name: 'Grammarly', logo: '<img src="https://ik.imagekit.io/bensusx9i/jdjfvbjbj-removebg-preview_35_11zon.webp" alt="Grammarly Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://www.grammarly.com/', article: `<p>Grammarly is far more than a spelling and grammar checker; it's a comprehensive AI-powered writing partner. It provides real-time feedback on your writing to help you improve clarity, tone, and style, ensuring your message is always communicated effectively and professionally.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Tone Detector:</strong> Analyzes your word choice and phrasing to identify the tone of your message (e.g., confident, friendly, analytical).</li><li><strong>Clarity and Conciseness:</strong> Suggests ways to rewrite confusing sentences and eliminate wordiness for more impactful writing.</li><li><strong>Generative AI Assistance:</strong> Helps you brainstorm, compose, and rewrite text directly within your documents and emails.</li></ul><p class="mt-4">Grammarly is an indispensable tool for students, professionals, and anyone who wants to communicate with confidence and precision.</p>` },
    { name: 'Writesonic', logo: '<img src="https://ik.imagekit.io/bensusx9i/jkfhjvnv_34_11zon.webp" alt="Writesonic Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://writesonic.com/', article: `<p>Writesonic is a versatile AI writer designed to help you create SEO-friendly content for your blogs, ads, emails, and website at lightning speed. With a wide array of tools and templates, it streamlines the entire content creation process from idea to publication.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>AI Article Writer:</strong> Generate complete, plagiarism-free articles and blog posts in minutes, optimized for search engines.</li><li><strong>Landing Page Generator:</strong> Create high-converting landing pages with compelling copy and design, no coding required.</li><li><strong>Brand Voice:</strong> Train the AI on your existing content to ensure all future generations match your unique brand tone and style.</li></ul><p class="mt-4">Writesonic is a go-to platform for marketing teams, e-commerce stores, and agencies that need to produce high volumes of quality content efficiently.</p>` },
];

export const AUDIO_TOOLS: Tool[] = [
    { name: 'Murf.ai', logo: '<img src="https://ik.imagekit.io/bensusx9i/83059529_32_11zon.webp" alt="Murf.ai Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://murf.ai/', article: `<p>Murf.ai is a versatile text-to-speech platform that provides a vast library of studio-quality AI voices for your videos and presentations. Go from text to professional voiceover in minutes, with options to control pitch, speed, and emphasis for the perfect delivery.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Extensive Voice Library:</strong> Choose from over 120 human-like AI voices across 20+ languages and accents.</li><li><strong>AI Voice Changer:</strong> Upload your own raw voice recording, and the AI will transform it into a professional, studio-quality voiceover.</li><li><strong>Video & Music Integration:</strong> Add your voiceover directly to videos, images, or music within the Murf Studio for a complete production.</li></ul><p class="mt-4">Murf.ai is ideal for educators, content creators, and corporate trainers who need high-quality, consistent voiceovers for their projects.</p>` },
    { name: 'ElevenLabs', logo: '<img src="https://ik.imagekit.io/bensusx9i/hfhhbn_31_11zon.webp" alt="ElevenLabs Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://elevenlabs.io/', article: `<p>ElevenLabs is at the forefront of AI voice synthesis, renowned for producing the most realistic and emotionally expressive text-to-speech audio available. Its powerful models can generate lifelike speech for storytelling, create unique voices, and even produce a perfect digital clone of your own voice.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Generative Voice AI:</strong> Produce rich, natural-sounding speech in any voice and style, with the ability to convey nuanced emotions.</li><li><strong>Professional Voice Cloning:</strong> Create a flawless digital replica of your voice from just a few minutes of audio.</li><li><strong>AI Dubbing:</strong> Automatically translate your audio or video content into another language while preserving the original speaker's voice.</li></ul><p class="mt-4">ElevenLabs is the top choice for creators, developers, and businesses seeking the highest-quality AI voices for audiobooks, gaming, and content creation.</p>` },
    { name: 'Speechify', logo: '<img src="https://ik.imagekit.io/bensusx9i/8f38b537a39fd6abb27fdc313e3f02f6_33_11zon.webp" alt="Speechify Logo" loading="lazy" style="object-fit: contain; width: 100%; height: 100%;" />', url: 'https://speechify.com/', article: `<p>Speechify is a leading text-to-speech app that turns any reading material into interactive audio. With its intelligent AI voices, you can listen to documents, articles, emails, and PDFs, helping you consume content faster, improve focus, and increase retention.</p><h3 class="text-xl font-bold text-gray-100 mt-6 mb-2">AI-Powered Features</h3><ul class="list-disc list-inside space-y-2"><li><strong>Natural-Sounding Voices:</strong> Listen to your content in a variety of high-quality AI voices and accents, including celebrity voices.</li><li><strong>Scan and Listen:</strong> Take a photo of any physical text, and Speechify's AI will read it aloud to you.</li><li><strong>Cross-Platform Syncing:</strong> Start listening on your phone and seamlessly continue on your computer or tablet.</li></ul><p class="mt-4">Speechify is an essential productivity tool for students, professionals, and anyone with reading difficulties, transforming the way you consume written information.</p>` },
];

export const CHATBOT_TOOLS: Tool[] = [
    { name: 'ChatGPT', logo: soraLogo, url: 'https://chat.openai.com/', article: placeholderArticle },
    { name: 'Google Gemini', logo: genericChatbotLogo, url: 'https://gemini.google.com/', article: placeholderArticle },
    { name: 'Tidio', logo: genericChatbotLogo, url: 'https://www.tidio.com/', article: placeholderArticle },
    { name: 'ManyChat', logo: genericChatbotLogo, url: 'https://manychat.com/', article: placeholderArticle },
    { name: 'Drift', logo: genericChatbotLogo, url: 'https://www.drift.com/', article: placeholderArticle },
    { name: 'Intercom', logo: genericChatbotLogo, url: 'https://www.intercom.com/', article: placeholderArticle },
    { name: 'Character.AI', logo: genericChatbotLogo, url: 'https://character.ai/', article: placeholderArticle },
];

export const CODING_TOOLS: Tool[] = [
    { name: 'GitHub Copilot', logo: genericCodeLogo, url: 'https://github.com/features/copilot', article: placeholderArticle },
    { name: 'Replit', logo: genericCodeLogo, url: 'https://replit.com/', article: placeholderArticle },
    { name: 'Tabnine', logo: genericCodeLogo, url: 'https://www.tabnine.com/', article: placeholderArticle },
    { name: 'Amazon CodeWhisperer', logo: genericCodeLogo, url: 'https://aws.amazon.com/codewhisperer/', article: placeholderArticle },
    { name: 'Mutable.ai', logo: genericCodeLogo, url: 'https://mutable.ai/', article: placeholderArticle },
    { name: 'Sourcegraph Cody', logo: genericCodeLogo, url: 'https://sourcegraph.com/cody', article: placeholderArticle },
];

export const RESEARCH_TOOLS: Tool[] = [
    { name: 'Perplexity AI', logo: genericResearchLogo, url: 'https://www.perplexity.ai/', article: placeholderArticle },
    { name: 'Elicit', logo: genericResearchLogo, url: 'https://elicit.org/', article: placeholderArticle },
    { name: 'Scite', logo: genericResearchLogo, url: 'https://scite.ai/', article: placeholderArticle },
    { name: 'Consensus', logo: genericResearchLogo, url: 'https://consensus.app/', article: placeholderArticle },
    { name: 'ChatPDF', logo: genericResearchLogo, url: 'https://www.chatpdf.com/', article: placeholderArticle },
    { name: 'Semantic Scholar', logo: genericResearchLogo, url: 'https://www.semanticscholar.org/', article: placeholderArticle },
];

export const BUSINESS_TOOLS: Tool[] = [
    { name: 'HubSpot AI', logo: genericBusinessLogo, url: 'https://www.hubspot.com/artificial-intelligence', article: placeholderArticle },
    { name: 'Zendesk AI', logo: genericBusinessLogo, url: 'https://www.zendesk.com/service/ai-bots/', article: placeholderArticle },
    { name: 'Salesforce Einstein', logo: genericBusinessLogo, url: 'https://www.salesforce.com/products/einstein/overview/', article: placeholderArticle },
    { name: 'AdCreative.ai', logo: genericBusinessLogo, url: 'https://www.adcreative.ai/', article: placeholderArticle },
    { name: 'Surfer SEO', logo: genericBusinessLogo, url: 'https://surferseo.com/', article: placeholderArticle },
    { name: 'Gong', logo: genericBusinessLogo, url: 'https://www.gong.io/', article: placeholderArticle },
];

export const PRODUCTIVITY_TOOLS: Tool[] = [
    { name: 'Notion AI', logo: genericProductivityLogo, url: 'https://www.notion.so/product/ai', article: placeholderArticle },
    { name: 'Motion', logo: genericProductivityLogo, url: 'https://www.usemotion.com/', article: placeholderArticle },
    { name: 'Todoist', logo: genericProductivityLogo, url: 'https://todoist.com/', article: placeholderArticle },
    { name: 'Zapier', logo: genericProductivityLogo, url: 'https://zapier.com/', article: placeholderArticle },
    { name: 'Fireflies.ai', logo: genericProductivityLogo, url: 'https://fireflies.ai/', article: placeholderArticle },
    { name: 'SaneBox', logo: genericProductivityLogo, url: 'https://www.sanebox.com/', article: placeholderArticle },
];

export const DATA_TOOLS: Tool[] = [
    { name: 'Tableau', logo: genericDataLogo, url: 'https://www.tableau.com/', article: placeholderArticle },
    { name: 'Power BI', logo: genericDataLogo, url: 'https://powerbi.microsoft.com/', article: placeholderArticle },
    { name: 'Julius AI', logo: genericDataLogo, url: 'https://julius.ai/', article: placeholderArticle },
    { name: 'Polymer', logo: genericDataLogo, url: 'https://www.polymersearch.com/', article: placeholderArticle },
    { name: 'Databricks', logo: genericDataLogo, url: 'https://www.databricks.com/', article: placeholderArticle },
    { name: 'Akkio', logo: genericDataLogo, url: 'https://www.akkio.com/', article: placeholderArticle },
];

export const EDUCATION_TOOLS: Tool[] = [
    { name: 'Khanmigo', logo: genericEducationLogo, url: 'https://www.khanacademy.org/khan-labs', article: placeholderArticle },
    { name: 'Quizlet', logo: genericEducationLogo, url: 'https://quizlet.com/', article: placeholderArticle },
    { name: 'Gradescope', logo: genericEducationLogo, url: 'https://www.gradescope.com/', article: placeholderArticle },
    { name: 'Socratic', logo: genericEducationLogo, url: 'https://socratic.org/', article: placeholderArticle },
    { name: 'Coursera', logo: genericEducationLogo, url: 'https://www.coursera.org/', article: placeholderArticle },
];

export const HEALTHCARE_TOOLS: Tool[] = [
    { name: 'Ada Health', logo: genericHealthcareLogo, url: 'https://ada.com/', article: placeholderArticle },
    { name: 'Woebot Health', logo: genericHealthcareLogo, url: 'https://woebothealth.com/', article: placeholderArticle },
    { name: 'Babylon Health', logo: genericHealthcareLogo, url: 'https://www.babylonhealth.com/', article: placeholderArticle },
    { name: 'MyFitnessPal', logo: genericHealthcareLogo, url: 'https://www.myfitnesspal.com/', article: placeholderArticle },
];

export const LEGAL_FINANCE_TOOLS: Tool[] = [
    { name: 'LawGeex', logo: genericLegalFinanceLogo, url: 'https://www.lawgeex.com/', article: placeholderArticle },
    { name: 'Casetext', logo: genericLegalFinanceLogo, url: 'https://casetext.com/', article: placeholderArticle },
    { name: 'QuickBooks', logo: genericLegalFinanceLogo, url: 'https://quickbooks.intuit.com/', article: placeholderArticle },
    { name: 'TaxAct', logo: genericLegalFinanceLogo, url: 'https://www.taxact.com/', article: placeholderArticle },
];

export const ECOMMERCE_TOOLS: Tool[] = [
    { name: 'Jasper', logo: genericEcommerceLogo, url: 'https://www.jasper.ai/', article: placeholderArticle },
    { name: 'Optimove', logo: genericEcommerceLogo, url: 'https://www.optimove.com/', article: placeholderArticle },
    { name: 'Persado', logo: genericEcommerceLogo, url: 'https://persado.com/', article: placeholderArticle },
    { name: 'ChatGPT', logo: genericEcommerceLogo, url: 'https://chat.openai.com/', article: placeholderArticle },
];

export const HR_RECRUITING_TOOLS: Tool[] = [
    { name: 'HireVue', logo: genericHrLogo, url: 'https://www.hirevue.com/', article: placeholderArticle },
    { name: 'Textio', logo: genericHrLogo, url: 'https://textio.com/', article: placeholderArticle },
    { name: 'Paradox', logo: genericHrLogo, url: 'https://www.paradox.ai/', article: placeholderArticle },
    { name: 'Eightfold.ai', logo: genericHrLogo, url: 'https://eightfold.ai/', article: placeholderArticle },
];

export const GAMING_TOOLS: Tool[] = [
    { name: 'Inworld AI', logo: genericGamingLogo, url: 'https://inworld.ai/', article: placeholderArticle },
    { name: 'Scenario', logo: genericGamingLogo, url: 'https://www.scenario.com/', article: placeholderArticle },
    { name: 'Ludo.ai', logo: genericGamingLogo, url: 'https://ludo.ai/', article: placeholderArticle },
    { name: 'Charisma.ai', logo: genericGamingLogo, url: 'https://charisma.ai/', article: placeholderArticle },
];

export const STORYTELLING_TOOLS: Tool[] = [
    { name: 'Sudowrite', logo: genericStorytellingLogo, url: 'https://www.sudowrite.com/', article: placeholderArticle },
    { name: 'NovelAI', logo: genericStorytellingLogo, url: 'https://novelai.net/', article: placeholderArticle },
    { name: 'Plot Factory', logo: genericStorytellingLogo, url: 'https://plotfactory.com/', article: placeholderArticle },
    { name: 'Campfire', logo: genericStorytellingLogo, url: 'https://www.campfirewriting.com/', article: placeholderArticle },
];

export const AUTOMATION_TOOLS: Tool[] = [
    { name: 'Zapier', logo: genericAutomationLogo, url: 'https://zapier.com/', article: placeholderArticle },
    { name: 'Make', logo: genericAutomationLogo, url: 'https://www.make.com/', article: placeholderArticle },
    { name: 'IFTTT', logo: genericAutomationLogo, url: 'https://ifttt.com/', article: placeholderArticle },
    { name: 'n8n', logo: genericAutomationLogo, url: 'https://n8n.io/', article: placeholderArticle },
];

export const SEARCH_DISCOVERY_TOOLS: Tool[] = [
    { name: 'Perplexity AI', logo: genericResearchLogo, url: 'https://www.perplexity.ai/', article: placeholderArticle },
    { name: 'You.com', logo: genericResearchLogo, url: 'https://you.com/', article: placeholderArticle },
    { name: 'Phind', logo: genericResearchLogo, url: 'https://www.phind.com/', article: placeholderArticle },
    { name: 'Andi', logo: genericResearchLogo, url: 'https://andisearch.com/', article: placeholderArticle },
];

export const SECURITY_PRIVACY_TOOLS: Tool[] = [
    { name: 'Darktrace', logo: genericSecurityLogo, url: 'https://www.darktrace.com/', article: placeholderArticle },
    { name: 'CrowdStrike', logo: genericSecurityLogo, url: 'https://www.crowdstrike.com/', article: placeholderArticle },
    { name: 'Sift', logo: genericSecurityLogo, url: 'https://sift.com/', article: placeholderArticle },
    { name: 'Auth0', logo: genericSecurityLogo, url: 'https://auth0.com/', article: placeholderArticle },
];

export const EXPERIMENT_SANDBOX_TOOLS: Tool[] = [
    { name: 'Hugging Face', logo: genericSandboxLogo, url: 'https://huggingface.co/', article: placeholderArticle },
    { name: 'OpenAI Playground', logo: genericSandboxLogo, url: 'https://platform.openai.com/playground', article: placeholderArticle },
    { name: 'Replicate', logo: genericSandboxLogo, url: 'https://replicate.com/', article: placeholderArticle },
    { name: 'Google Colab', logo: genericSandboxLogo, url: 'https://colab.research.google.com/', article: placeholderArticle },
];